name: Rebuild and Deploy Static Site

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pandoc \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libpng-dev \
          libtiff5-dev \
          libjpeg-dev

    - name: Retrieve and Export R Version
      id: r_version
      run: |
        echo "R_VERSION=$(R --version | head -n 1 | awk '{print $3}' | sed 's/[[:alpha:]]//g')" >> $GITHUB_ENV

    - name: Check R Library Paths
      run: Rscript -e '.libPaths()'

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: /home/runner/work/_temp/Library
        key: ${{ runner.os }}-r-${{ env.R_VERSION }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Install Required R Packages
      run: |
        Rscript -e "
          options(repos = 'https://cloud.r-project.org');
          .libPaths('/home/runner/work/_temp/Library');
          install.packages(c(
            'rmarkdown', 'knitr', 'dplyr', 'lubridate', 'dtwclust', 
            'ggthemes', 'ggrepel', 'tidyr', 'readr', 'plotly',
            'ggplot2', 'tsfeatures', 'tidymodels', 'purrr',
            'stringr', 'caret', 'randomForest', 'tibble'))
        "
        
    - name: Check Pandoc Version
      run: pandoc --version

    - name: Knit R Markdown (with error handling)
      run: |
        Rscript -e "
          tryCatch({
            rmarkdown::render_site()
          }, error = function(e) {
            message('Error during knitting: ', e$message)
          })
        "

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Automated update: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

